### ISSUE TITLE
HTML files do not reflect code in video

### ISSUE THREAD

**Issue by flats** [learn-co-students/htm-css-code-along-3-001-prework-web#10]
The HTML files in this repo do not reflect the state of the files in the video. They're basically the same files from html5-video-embed-code-along-v-000. Because there's no text file included with the necessary content, pretty much the only way to complete this lab is to copy HTML content from the video into these HTML files.

**Comment by patrocc6** [comment]
Same issue. The HTML files in this lab are not updated with the content shown in the video.

**Comment by molotov2k** [comment]
Problem still there. On 14:30 i also believe it should say "Times New Roman", not "New Times Roman".

**Comment by jongrover** [comment]
@flats  @patrocc6 @molotov2k just re-deployed this lesson, code looks good now. Thanks for notice not sure why it didnt get the most recent updates until now.
